# RSP Training Portal — Image rename and organize script
# ----------------------------------------------------------
# Generated by Claude after visually classifying ~235 images dropped into
# portal/images/. This script:
#   1. Creates subfolders: accessories/, enclosures/, electrical/, extras/
#   2. Moves the 32 confidently identified images into their proper folder + name
#   3. Moves all UNUSED hash-named images into extras/ for your manual review
#
# How to run:
#   1. Open PowerShell (right-click Start -> "Windows PowerShell" or "Terminal")
#   2. cd "C:\Users\sasuk\OneDrive\Desktop\portal"
#   3. powershell -ExecutionPolicy Bypass -File .\rename-images.ps1
#
# It is SAFE to re-run: already-moved files are skipped.
# It uses Move-Item (not Copy), so the originals in images/ root will be removed
# after a successful move.

$ErrorActionPreference = "Stop"
$base = "C:\Users\sasuk\OneDrive\Desktop\portal\images"

if (-not (Test-Path $base)) {
    Write-Error "Images folder not found at $base. Aborting."
    exit 1
}

# ---- 1. Ensure subfolders exist ----
foreach ($sub in @("accessories", "enclosures", "electrical", "extras")) {
    $path = Join-Path $base $sub
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path | Out-Null
        Write-Host "Created folder: $sub" -ForegroundColor Cyan
    }
}

# ---- 2. The mappings: source hash filename -> target subfolder/filename ----
# Note: the source files are .png but the targets use .jpg. Browsers content-sniff
# local image files, so a PNG saved as .jpg displays correctly.
$mappings = @(
    # ACCESSORIES (16) ----------------------------------------------------
    @{ src = "c2d8b52c30fa74e76a9fbaff52506778.png"; dst = "accessories\hero-mounting-1.jpg";       desc = "Stainless steel backplate with roof assembly" },
    @{ src = "ec39b896-7723-4223-abb7-db56faec220a.png"; dst = "accessories\hero-mounting-2.jpg";   desc = "Steel shelf rack mounted, double-sided" },
    @{ src = "f1a6e18500ec4cbb8b97f57f52503329.png"; dst = "accessories\hero-cable-1.jpg";          desc = "Cable duct slotted wire routing system" },
    @{ src = "a49f8d44-933d-4c69-9bc1-899a3d29f815.png"; dst = "accessories\hero-cable-2.jpg";      desc = "Cable entry roof plate gland plate, multiple ports" },
    @{ src = "d55dce41-1cc8-44e3-8425-6b96d1a6cf8d.png"; dst = "accessories\hero-thermal-1.jpg";    desc = "Filter fan shroud, washdown" },
    @{ src = "21b5425d-6d4b-4893-afb2-c7f2b81cce96.png"; dst = "accessories\hero-thermal-2.jpg";    desc = "Rittal roof plate ventilation enclosure" },
    @{ src = "4b7df905-edb6-41da-b31f-25fd0f0fc4b5.png"; dst = "accessories\hero-protection.jpg";   desc = "Stainless steel canopy/overhang for outdoor cabinet" },
    @{ src = "1409ebc057ce312829bd5dcf52506600.png"; dst = "accessories\gland-plate.jpg";           desc = "Gasketed gland plate with cable knockouts" },
    @{ src = "3bcadf4d219386337b0f719f51829573.png"; dst = "accessories\swing-out-panel.jpg";       desc = "Swing-out panel kit for electrical enclosure" },
    @{ src = "2ec0f8242291f63f66463e4f51829413.png"; dst = "accessories\latch-handle.jpg";          desc = "Wall-mount latch handle with keyed lock" },
    @{ src = "b8b880a617fb0c9525472b0f51829663.png"; dst = "accessories\wire-duct-slotted.jpg";     desc = "Slotted wire duct, cable routing" },
    @{ src = "6e87593fd80ba36b0444a76f52518066.png"; dst = "accessories\grommets-hole-seals.jpg";   desc = "Variety of grommets and hole-seal plugs" },
    @{ src = "008e9445-2ff4-4e1f-8b7e-35728cce3460.png"; dst = "accessories\filter-fan.jpg";        desc = "Filter fan with finger guard" },
    @{ src = "3a53523e-2955-4bac-82e7-5add75d76eb0.png"; dst = "accessories\enclosure-ac.jpg";      desc = "Spectracool air conditioner unit" },
    @{ src = "2fd4d8f4-1353-420d-a2ac-e95b8e7411c3.png"; dst = "accessories\enclosure-heater.jpg";  desc = "Electric heater 230V 800W, DIN rail" },
    @{ src = "ee66f639-186d-45dd-8812-872b0914e69a.png"; dst = "accessories\sun-shield.jpg";        desc = "COMLINE solar shield, outdoor cabinet" },

    # ENCLOSURES (11) -----------------------------------------------------
    @{ src = "0633cf15-1d51-48a1-af6a-9a18686bf299.png"; dst = "enclosures\hero-enclosure-basics.jpg";       desc = "Eaton industrial pump control panel, NEMA" },
    @{ src = "c9438fc94430d5ca2e0083ff52506053.png"; dst = "enclosures\hero-nonmetallic-cabinet.jpg";        desc = "Fiberglass/polycarbonate enclosure cabinet" },
    @{ src = "282176fb-2d03-4e6a-95ff-62bfe42fae70.png"; dst = "enclosures\hero-nema-rated.jpg";             desc = "ACI humidity sensor in NEMA 4X enclosure outdoor" },
    @{ src = "2c23b405b120c6d978a8af1f51801385.png"; dst = "enclosures\mfr-hoffman.jpg";                     desc = "nVent Hoffman brand logo" },
    @{ src = "184f175d2bc26e86f13648bf52497697.png"; dst = "enclosures\mfr-rittal.jpg";                      desc = "Rittal AX compact wall-mount enclosure" },
    @{ src = "91c239ad6c45f0c3c101102f51801435.png"; dst = "enclosures\mfr-stahlin.jpg";                     desc = "Stahlin brand logo" },
    @{ src = "063c91a58c01aa127da10c5f52506372.png"; dst = "enclosures\mfr-allied-moulded.jpg";              desc = "Small polycarbonate wall-mount enclosure" },
    @{ src = "1decf804-3a4b-44ed-bbea-97de7dd05cba.png"; dst = "enclosures\mfr-schneider.jpg";               desc = "Schneider Electric brand logo" },
    @{ src = "ce344ec651ba295f1ca4979f51801523.png"; dst = "enclosures\mfr-killark.jpg";                     desc = "Killark brand logo" },
    @{ src = "7216658b-b017-4d09-a644-bc995c8bb61b.png"; dst = "enclosures\mfr-adalet.jpg";                  desc = "Adalet hazardous junction box" },
    @{ src = "daf689252132514d4791e91f51801574.png"; dst = "enclosures\mfr-phoenix-contact.jpg";             desc = "Phoenix Contact DIN rail enclosure housing" },

    # ELECTRICAL (5) ------------------------------------------------------
    @{ src = "cd297a6a-b9fa-4d42-9d0f-3f7ee34294e1.png"; dst = "electrical\hero-three-phase.jpg";    desc = "Nidec TEAO three-phase industrial motor" },
    @{ src = "69143f90-a4f6-48bd-a252-e61127616ecb.png"; dst = "electrical\hero-motor-nameplate.jpg"; desc = "Hands holding motor with nameplate visible" },
    @{ src = "02e44a49-427e-4815-8c90-1d6ea774c987.png"; dst = "electrical\hero-vfd.jpg";            desc = "Eaton DM1 series wall-mount VFD" },
    @{ src = "04c03295fdbfd6b90b99ccff51819943.png"; dst = "electrical\ice-cube-breaker.jpg";        desc = "Pair of ice cube breakers, black" },
    @{ src = "23400fc2-9b99-4a0d-be3a-1b73a0873e6d.png"; dst = "electrical\contactor.jpg";           desc = "Eaton 3-pole motor contactor, side angle" }
)

# ---- 3. Apply the mappings ----
$moved = 0
$missing = 0
$alreadyDone = 0
foreach ($m in $mappings) {
    $src = Join-Path $base $m.src
    $dst = Join-Path $base $m.dst

    if (Test-Path $dst) {
        Write-Host "  SKIP (target already exists): $($m.dst)" -ForegroundColor DarkGray
        $alreadyDone++
        continue
    }
    if (-not (Test-Path $src)) {
        Write-Warning "  SOURCE NOT FOUND: $($m.src)  (target was: $($m.dst))"
        $missing++
        continue
    }

    Move-Item -Path $src -Destination $dst -Force
    Write-Host "  $($m.src) -> $($m.dst)" -ForegroundColor Green
    $moved++
}

Write-Host ""
Write-Host "Renames complete: $moved moved, $alreadyDone already in place, $missing source files missing." -ForegroundColor Cyan

# ---- 4. Move all remaining hash-named files in images/ root into extras/ ----
# We treat any file in the root of images/ (not in a subfolder) that's NOT
# README.md as an "extra" — it didn't get matched to a target.
Write-Host ""
Write-Host "Moving leftover images to extras/ ..." -ForegroundColor Cyan
$leftovers = Get-ChildItem -Path $base -File | Where-Object {
    $_.Name -ne "README.md" -and
    ($_.Extension -in @(".png", ".jpg", ".jpeg"))
}

$leftoverCount = 0
foreach ($f in $leftovers) {
    $dest = Join-Path $base "extras\$($f.Name)"
    if (-not (Test-Path $dest)) {
        Move-Item -Path $f.FullName -Destination $dest -Force
        $leftoverCount++
    }
}
Write-Host "  $leftoverCount files moved to extras/"

# ---- 5. Summary ----
Write-Host ""
Write-Host "===== DONE =====" -ForegroundColor Green
Write-Host "  $moved images renamed and organized into the right subfolders"
Write-Host "  $leftoverCount extra/unmatched images moved to images\extras\ for your review"
Write-Host ""
Write-Host "Targets that did NOT get a matching image (will show 'Photo coming soon' placeholder):" -ForegroundColor Yellow
$missingTargets = @(
    "accessories\hero-five-groups.jpg",
    "accessories\cable-manager-vertical.jpg",
    "enclosures\hero-enclosure-jobs.jpg",
    "enclosures\hero-rsp-brands.jpg",
    "enclosures\hero-three-decisions.jpg",
    "enclosures\hero-steel-cabinet.jpg",
    "electrical\hero-water-analogy.jpg",
    "electrical\hero-ac-dc.jpg",
    "electrical\hero-grounding.jpg",
    "electrical\hero-ul-breakers.jpg",
    "electrical\hero-relay-contactor.jpg",
    "electrical\hero-ladder-schematic.jpg",
    "electrical\relay.jpg",
    "electrical\power-supply-24vdc.jpg"
)
foreach ($t in $missingTargets) {
    Write-Host "  - $t" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Tip: dig through images\extras\ to see if any of those leftovers match the missing targets above."
Write-Host "If you find one, just rename it manually to the target filename and drop it in the right subfolder."
